title: "Jeewan Adhikari"
description: "Water Resources • Flood Modeling • GIS • Python"
url: "https://jeewanadhikari.github.io"
baseurl: ""
classes: wide


remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"
repository: "jeewanadhikari/jeewanadhikari.github.io"


plugins:
  - jekyll-include-cache
  - jekyll-sitemap

# show sidebar profile on pages
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

author:
  name: "Jeewan Adhikari"
  avatar: "/assets/images/jeewan.jpg"
  bio: "Civil Engineering (Water Resources)"
  location: "Nepal"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:077bce065.jeewan@pcampus.edu.np"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/jeewanadhikari"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/jeewan-adhikari/"
   
